### ISSUE TITLE
a little exploration of the default css for scrollbars

### ISSUE THREAD

**Issue by paulovieira** [paulovieira/roam-scrollbars#1]
CSS styles are located in 2 files:
- https://roamresearch.com/assets/css/re-com/re-com.min.css 
- https://roamresearch.com/assets/css/less-compiled/site.css

Roam loads the first file and we get this:

```css

::-webkit-scrollbar {
	width: 10px;
	border-radius: 5px;
	background-color: rgba(0,0,0,.05);
}

::-webkit-scrollbar:horizontal {
	height: 10px;
}

::-webkit-scrollbar:hover {
	background-color: rgba(0,0,0,.2);
}

::-webkit-scrollbar-thumb:horizontal,
::-webkit-scrollbar-thumb:vertical {
	background: rgba(0,0,0,.25);
	border-radius: 5px;
}

::-webkit-scrollbar-thumb:horizontal:active,
::-webkit-scrollbar-thumb:vertical:active {
	background: rgba(0,0,0,.45);
}

```

Then loads the second file. It will override some of the styles above.
```css

#scroll-1::-webkit-scrollbar-track {
	-webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
	border-radius: 8px;
	background-color: #F5F5F5;
}

#scroll-1::-webkit-scrollbar {
	width: 8px;
	background-color: #F5F5F5;
}

#scroll-1::-webkit-scrollbar-thumb {
	border-radius: 8px;
	-webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
	background-color: #8A9BA8;
}

.rm-hide-scrollbar::-webkit-scrollbar {
	display: none;
}

.rm-settings ::-webkit-scrollbar:vertical {
	width: 8px;
	background: #293742;
}

.rm-settings ::-webkit-scrollbar-thumb {
	border-radius: 6px;
	background-color: #8A9BA8;
}

.rm-extensions-marketplace ::-webkit-scrollbar {
	width: 8px;
}

::-webkit-scrollbar {
	width: 0px;
	max-height: 4px;
	background: transparent;
}
```

CONCLUSION: the last ruleset in the second file makes the scrollbar invisible (because of `width: 0px;`)
